on: [push]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install wasm-pack --version 0.9.1
      - name: Annotate commit with clippy warnings
        uses: action-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
      - run: npm install
      - run: npm run build
